# Generated by Django 3.0.6 on 2020-08-18 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('pin_code', models.CharField(max_length=30, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question_own',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='own.Persona'),
        ),
    ]
