# Generated by Django 3.0.6 on 2020-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0002_auto_20200819_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
