# Generated by Django 3.0.6 on 2020-08-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('own', '0003_persona_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona_2',
        ),
    ]
