# Generated by Django 3.0.6 on 2020-06-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cret_text', models.CharField(max_length=200)),
            ],
        ),
    ]
