# Generated by Django 3.0.6 on 2020-08-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('pin', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
