# Generated by Django 3.0.6 on 2020-06-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200627_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
