# Generated by Django 3.0.6 on 2020-06-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200629_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='age',
            name='message',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='age',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
