# Generated by Django 3.0.6 on 2020-06-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200629_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='id',
        ),
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
