# Generated by Django 3.0.6 on 2020-06-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200629_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='age',
            old_name='age',
            new_name='age_2',
        ),
    ]
