# Generated by Django 3.0.6 on 2020-06-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200629_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='age_2',
        ),
        migrations.AddField(
            model_name='age',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='age',
            name='n',
            field=models.CharField(default='zero', max_length=200, primary_key=True, serialize=False),
        ),
    ]
