# Generated by Django 3.0.6 on 2020-06-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200629_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='n',
        ),
        migrations.AddField(
            model_name='age',
            name='id',
            field=models.AutoField(auto_created=True, default='default zero', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
