# Generated by Django 3.0.6 on 2020-08-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200630_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
