# Generated by Django 3.0.6 on 2020-08-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200812_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
