# Generated by Django 3.0.6 on 2020-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200812_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='age',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
