# Generated by Django 3.0.6 on 2020-06-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200610_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='cod_2',
        ),
        migrations.RemoveField(
            model_name='code',
            name='cod_3',
        ),
        migrations.AlterField(
            model_name='code',
            name='my_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
