# Generated by Django 3.0.6 on 2020-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200610_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='cod_2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='cod_3',
            field=models.CharField(default='default code', max_length=200),
            preserve_default=False,
        ),
    ]
