# Generated by Django 3.0.6 on 2020-06-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200610_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
