# Generated by Django 3.0.6 on 2020-06-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='my_code',
            new_name='my_code_1',
        ),
    ]
