# Generated by Django 3.0.6 on 2020-06-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200610_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='my_code_1',
        ),
        migrations.AddField(
            model_name='code',
            name='my_code',
            field=models.ForeignKey(default='default_code', on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
    ]
