# Generated by Django 3.0.6 on 2020-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200610_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='my_code',
            field=models.CharField(max_length=200),
        ),
    ]
