# Generated by Django 3.0.6 on 2020-06-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='age',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
