# Generated by Django 3.0.6 on 2020-06-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Message'),
        ),
    ]
