# Generated by Django 3.0.6 on 2020-06-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_pin_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='message',
            new_name='message_0',
        ),
    ]
