# Generated by Django 3.0.6 on 2020-06-18 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20200616_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='user_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Information'),
        ),
    ]
