# Generated by Django 3.0.6 on 2020-06-20 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_pin_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='age',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='pin',
            name='user_quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
