# Generated by Django 3.0.6 on 2020-06-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200621_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='information',
            old_name='quantity',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='user_quantity',
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Q')),
            ],
        ),
    ]
