# Generated by Django 3.0.6 on 2020-06-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20200621_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='quantity_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
