# Generated by Django 3.0.6 on 2020-06-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_class_quantity_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Clas',
        ),
    ]
