# Generated by Django 3.0.6 on 2020-07-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20200621_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='own',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
